version: "3"

services:
  jenkins:
    image: 'custom/jenkins'
    container_name: jenkins
    hostname: jenkins
    networks: 
      - net_integration
    ports:
      - '8181:8080'
      - '50000:50000'
    volumes:
      - './jenkins:/var/jenkins_home'

  sonarqube:
    image: 'sonarqube'
    container_name: sonarqube
    hostname: sonarqube
    networks: 
      - net_integration
    ports: 
      - 9000:9000
    volumes:
      - ./sonarqube/conf:/opt/sonarqube/conf
      - ./sonarqube/extensions:/opt/sonarqube/extensions
      - ./sonarqube/logs:/opt/sonarqube/logs
      - ./sonarqube/data:/opt/sonarqube/data
 # nexus:
    #image: 'sonatype/nexus3'
   # container_name: nexus3
   # hostname: nexus3
   # networks: 
   #   - net_integration
   # ports: 
   #   - 8081:8081
   # volumes:
  #    - "nexus-data:/nexus-data"

networks:
  net_integration: